name: IventWar
version: 1.0
main: org.Main.iventWar.IventWar
api-version: 1.20
authors: [IventWar Team]
description: Team management plugin
commands:
  team:
    description: Main team command
    usage: /team <subcommand>
  myteam:
    description: Show your team menu
    usage: /myteam
  tc:
    description: Team chat
    usage: /tc <message>
  topbro:
    description: Secret command
    usage: /topbro
